name: Build Discord Mod

on:
  workflow_dispatch:

jobs:
  inject:
    runs-on: macos-latest
    steps:
      - name: Cai dat Azule
        run: |
          brew install ldid
          git clone https://github.com/Al4ise/Azule ~/Azule
          sudo ln -sf ~/Azule/azule /usr/local/bin/azule

      - name: Tai Discord goc va Loader Tweak
        run: |
          curl -L -k -o discord.ipa "https://github.com/nrzsh6sbzm-netizen/Discord-mod-apo/releases/download/V1.0/Discord_ASD_335.0_v1.0.ipa"
          curl -L -k -o tweak.dylib "https://github.com/revenge-mod/Revenge/releases/latest/download/Revenge.dylib"

      - name: Kiem tra file truoc khi tiem
        run: |
          ls -lh discord.ipa
          ls -lh tweak.dylib

      - name: Tiem Tweak vao Discord
        run: |
          azule -i discord.ipa -o output -f tweak.dylib -m

      - name: Xuat file Discord Mod hoan chinh
        uses: actions/upload-artifact@v4
        with:
          name: DiscordMod-IPA
          path: output/*.ipa
