name: Build Discord Mod

on:
  workflow_dispatch:

jobs:
  inject:
    runs-on: macos-latest
    permissions:
      contents: read
    steps:
      - name: Cai dat Azule va Cong cu ho tro
        run: |
          brew install ldid dpkg
          git clone https://github.com/Al4ise/Azule ~/Azule
          sudo ln -sf ~/Azule/azule /usr/local/bin/azule

      - name: Tu dong tai IPA va Mod
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 1. Lay file IPA tu Release
          gh release download --repo ${{ github.repository }} --pattern "*.ipa"
          mv *.ipa discord.ipa
          
          # 2. Lay Loader dylib (dung Enmity link truc tiep, khong lo 404)
          curl -L -o tweak.dylib "https://github.com/enmity-mod/tweak/releases/latest/download/Enmity.dylib"

      - name: Tiem Tweak vao Discord
        run: |
          azule -i discord.ipa -o output -f tweak.dylib -m

      - name: Xuat file Discord Mod
        uses: actions/upload-artifact@v4
        with:
          name: DiscordMod-IPA
          path: output/*.ipa
